### ISSUE TITLE
Styling is broken on IE11, label covers input text

### ISSUE THREAD

**Issue by liambrozik** [AlaskaAirlines/ods-inputtext#15]
## Describe the bug
When I render the inputtext on IE11 the styling appears to be broken

In the screenshot below, the "Passenger's last name" label is covering the inputted text "Brozik"

## To Reproduce
Try rendering the ods-inputtext in IE11. I used React but that doesn't seem to be the problem here.

## Expected behavior
The text input should be at least usable.

## Screenshots
![example-image](https://user-images.githubusercontent.com/17190016/83069062-247f3180-a01e-11ea-8b7a-a08736292700.png)

**Comment by blackfalcon** [comment]
Added to the backlog for review.

**Comment by blackfalcon** [comment]
oops o_0

**Comment by geoffrey1218** [comment]
I've done some research and I've figured out why this is happening. It's not very well documented so it took some digging. This issue is not `ods-inputtext` specific, and could occur when using any Auro component that uses design token custom properties in IE11 (see also [this auro-button issue](https://github.com/AlaskaAirlines/ods-button/issues/32)). The problem is due to how the ShadyCSS polyfill treats custom properties. Here's what happens:

1. ShadyCSS encounters the usage of a CSS custom property
2. It tries to find a value for that variable from within the component and fails because we define our tokens at the root of the document (see [this ShadyCSS issue](https://github.com/webcomponents/polyfills/issues/9))
3. It removes the variable declaration altogether

Normally, this is fine because we declare fallback styles. However, it gets tricky when the custom property is used as part of a rule with other constant, non-variable values. 

Here's an example. The component's build outputs the following in `style-css.js`:
```css
.inputText {
  border: 0 solid #58606c;
  border: 0 solid var(--color-base-shark);
  border-radius: 0;
  border-width: 0 0 1px;
  border-width: 0 0 var(--border-width-thin);
  padding: 2rem 2rem 0.5rem 0;
  padding: var(--size-scale-xl) var(--size-scale-xl) var(--size-scale-sml) 0;
  position: relative;
  -webkit-transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  -o-transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  width: 100%;
  font-size: var(--size-breakpoint-all-med);
  caret-color: #0074cb;
  caret-color: var(--color-brand-blue-atlas-base);
  background-color: transparent;
}
```
ShadyCSS transforms it into this:
```css
.ods-inputtext-1 .inputText.ods-inputtext {
  border: 0 solid #58606c;
  border: 0 solid; /* Also affected */
  border-radius: 0;
  border-width: 0 0 1px;
  border-width: 0 0; /* Also affected */
  padding: 2rem 2rem 0.5rem 0;
  padding: 0; /* ***Here's the problem*** */
  position: relative;
  -webkit-transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  -o-transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  transition: all 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
  width: 100%;
  font-size: ; /* Also affected */
  caret-color: #0074cb;
  caret-color: ; 
  background-color: transparent;
}
```

Note that the variables were removed from the padding declaration, but the rule is **still valid**. So due to the cascade, the browser removes padding from the element.

Note that the property was also removed from caret-color, but since doing so made the rule invalid, the browser used the (still valid) fallback declaration.

Here are some ways to fix this:
1. Include all design token custom properties within the style tag of each component. This will allow ShadyCSS to replace them with the appropriate value. However, this would require consumers to update their components whenever the design tokens update, which I think is a deal-breaker.
2. Any CSS rule using a design token needs to either only contain custom properties or contain no custom properties. This will prevent ShadyCSS from leaving an incorrect (but syntactically correct) rule. To accomplish this, we could either make new design tokens or break up shorthand rules. For example:
```css
.inputText {
  /* How we've been writing it */
  border: 0 solid var(--color-base-shark); 
  /* Rewrite to break up shorthand properties */
  border-width: 0;
  border-style: solid;
  border-color: var(--color-base-shark);
  /* Rewrite with new design tokens */
  border: var(--zero-token) var(--solid-token) var(--color-base-shark);
}
```

I think option 2 could work as a solution. It would mostly apply to border, padding, and margin, as far as I can tell. Ideally we could enforce this practice through linting/post-processing. I can start putting together a PR with the necessary updates to the component, but wanted to talk through what I found first.
